
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instagram0-2
    username: root
    password: DLWlsdn1!!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          url: jdbc:mysql://localhost:3306/instagram0-3